---
- name: Tags in Ansible
  hosts: all
  tasks:
   - name: Install tree
     apt:
      name: tree
      state: present
     tags: tree_installtion
   - name: User creation
     user:
      name: Ramesh
      password: intelliqit
     tags: user_creation
   - name: Copy /etc/paswd file
     copy:
      src: /etc/passwd
      dest: /tmp
...
