---
- name: Install firealld using hostscope varibales
  hosts: 172.31.36.172
  tasks:
   - name: Install firewalld
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...      
