---
# vars file for tomcat
pkg1: tomcat8
pkg2: tomcat8-admin
state1: present
state2: restarted
cache1: yes
cache2: no
file1: tomcat-users.xml
dest1: /etc/tomcat8
port1: 8080
port2: 9090
path1: /etc/tomcat8/server.xml
server1: http://172.31.10.86:9090
server2: http://172.31.10.94:9090
status1: 200
...
